/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormulaRouteImport } from './routes/formula'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SparkListRouteImport } from './routes/spark-list'
import { Route as WhoItsForRouteImport } from './routes/who-its-for'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulaRoute = FormulaRouteImport.update({
  id: '/formula',
  path: '/formula',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkListRoute = SparkListRouteImport.update({
  id: '/spark-list',
  path: '/spark-list',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoItsForRoute = WhoItsForRouteImport.update({
  id: '/who-its-for',
  path: '/who-its-for',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formula': typeof FormulaRoute
  '/founder': typeof FounderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spark-list': typeof SparkListRoute
  '/who-its-for': typeof WhoItsForRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formula': typeof FormulaRoute
  '/founder': typeof FounderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spark-list': typeof SparkListRoute
  '/who-its-for': typeof WhoItsForRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formula': typeof FormulaRoute
  '/founder': typeof FounderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spark-list': typeof SparkListRoute
  '/who-its-for': typeof WhoItsForRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formula'
    | '/founder'
    | '/sitemap.xml'
    | '/spark-list'
    | '/who-its-for'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/formula'
    | '/founder'
    | '/sitemap.xml'
    | '/spark-list'
    | '/who-its-for'
  id:
    | '__root__'
    | '/'
    | '/formula'
    | '/founder'
    | '/sitemap.xml'
    | '/spark-list'
    | '/who-its-for'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormulaRoute: typeof FormulaRoute
  FounderRoute: typeof FounderRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SparkListRoute: typeof SparkListRoute
  WhoItsForRoute: typeof WhoItsForRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formula': {
      id: '/formula'
      path: '/formula'
      fullPath: '/formula'
      preLoaderRoute: typeof FormulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spark-list': {
      id: '/spark-list'
      path: '/spark-list'
      fullPath: '/spark-list'
      preLoaderRoute: typeof SparkListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-its-for': {
      id: '/who-its-for'
      path: '/who-its-for'
      fullPath: '/who-its-for'
      preLoaderRoute: typeof WhoItsForRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormulaRoute: FormulaRoute,
  FounderRoute: FounderRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SparkListRoute: SparkListRoute,
  WhoItsForRoute: WhoItsForRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
